"use client";

const touristInfo = [
  {
    name: "Sylhet Tea Gardens",
    image:"/teagarden.jpg",
    description: "Explore the beautiful tea gardens.",
    days: 5,
    rating: 4.8,
    reviews: 350,
    originalPrice: 1250,
    discountedPrice: 999,
    discount: 20,
  },
  {
  name: "Bandarban Hills",
  image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4iiW5NLNSe6teUijqRknw9txL9MG4bwYaiQ&s",
    description: "Trekking and scenic beauty.",
    days: 7,
    rating: 4.7,
    reviews: 410,
    originalPrice: 1500,
    discountedPrice: 1200,
    discount: 20,
  },
  {
  name: "Rangamati Lake",
  image:"https://cosmosgroup.sgp1.digitaloceanspaces.com/news/details/6754470_suspension-bridge-kaptai-lake-rangamati.jpg",
    description: "Boating on the serene lake.",
    days: 3,
    rating: 4.6,
    reviews: 280,
    originalPrice: 800,
    discountedPrice: 680,
    discount: 15,
  },
  {
  name: "Cox's Bazar Beach",
  image:"https://www.dailypost.net/media/imgAll/2023September/coxs-bazar-20240928103318.jfif",
    description: "World's longest natural sea beach.",
    days: 4,
    rating: 4.9,
    reviews: 500,
    originalPrice: 1100,
    discountedPrice: 900,
    discount: 18,
  },
  {
  name: "Sundarbans Mangroves",
  image:"https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2024/01/16170702/tiger-1600x900.jpg",
    description: "Home of the Royal Bengal Tiger.",
    days: 6,
    rating: 4.9,
    reviews: 450,
    originalPrice: 2000,
    discountedPrice: 1500,
    discount: 25,
  },
  {
  name: "Bagerhat Mosques",
  image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_bbMrkAZGi7U6imEaVyYvD5CB65RK_SP-5w&s",
    description: "Historical Mosque City.",
    days: 2,
    rating: 4.5,
    reviews: 150,
    originalPrice: 500,
    discountedPrice: 425,
    discount: 15,
  },
  {
  name: "Dhaka Old City",
  image:"https://upload.wikimedia.org/wikipedia/commons/1/1f/DhakaCity1861.png",
    description: "Explore historical sites.",
    days: 1,
    rating: 4.4,
    reviews: 200,
    originalPrice: 300,
    discountedPrice: 250,
    discount: 17,
  },
  {
  name: "Rajshahi Varendra Museum",
  image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkdX-__kstMiEtN5zd9OX8chQqgdDLAaSYNg&s",
    description: "Visit the oldest museum.",
    days: 2,
    rating: 4.3,
    reviews: 120,
    originalPrice: 400,
    discountedPrice: 320,
    discount: 20,
  },
];

export default touristInfo;
